Nuvian_Web/Models/ErrorViewModel.cs
using System;

namespace Nuvian_Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Nuvian_Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Nuvian_Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BussinesLogic.Services;

namespace Nuvian_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IServiceAPI _service;

        public HomeController(ILogger<HomeController> logger, IServiceAPI service)
        {
            _logger = logger;
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult HomeView()
        {
            return View();
        }
      
        [HttpPost]
        public async Task<string> Login(string cedula, string contrasena)
        {
            bool resp;
            //Se envian los parametros a la interface para realizar la validacion del login, esta devuelve y bool (true/false) segun la accion con haya respondido la api
            resp = await _service.login(cedula, contrasena);
            return Convert.ToString(resp);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nuvian_Web/Controllers/MeteorologyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nuvian_Web.Controllers
{
    public class MeteorologyController : Controller
    {
        public IActionResult Iframe()
        {
            return View();
        }
    }
}

Nuvian_Web/Controllers/UserController.cs
using BussinesLogic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BussinesLogic.Models;

namespace Nuvian_Web.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IServiceAPI _service;
        public UserController(ILogger<UserController> logger, IServiceAPI service)
        {
            _logger = logger;
            _service = service;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BasePage()
        {
            return View();
        }



        [HttpPost]
        public bool NuevoUsuario(UserModel user)
        {
            try
            {
                return  _service.Create(user);
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpPost]
        public bool EliminarUsuario(UserModel user)
        {
            try
            {
             
                return _service.Delete(user.Id_usr); 

            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public async Task<JsonResult> ListarUsuarios()
        {

            List<UsuariosAll> list = new List<UsuariosAll>();
            list = await _service.ListarUsuarios();
            return Json(list);
        }

        [HttpGet]
        public async Task<JsonResult> CargarCombo()
        {
            List<AirportsModel.airportsList> airports = new List<AirportsModel.airportsList>();
            airports = await _service.ListarAeropuertos();

            return Json(airports);
        }

        [HttpGet]
        public async Task<JsonResult> BuscarUsarioID(int id)
        {
            List<UsuariosbyID> lst = await _service.ObtenerUsuario(id);
            return Json(lst);
        }

        [HttpPost]
        public async Task<bool> EditarUsuario(ActualizarUsuario actualizar)
        {
            return await _service.EditarUsuario(actualizar);
        }


    }
}

Nuvian_Web/Views/Home/HomeView.cshtml
@{
    ViewData["Title"] = "HomeView";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<body class="imgLogin  ">
    <header>
        <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse ">
            <br />

            <h3 class="text-center text-dark ">Administración</h3>

            <div class="position-sticky">
                <div class="list-group list-group-flush mx-3 mt-4">

                    <a asp-action="BasePage" asp-controller="User" class="list-group-item list-group-item-action py-2 ripple   etiquetas"><i style="color:dimgrey" class="bi bi-people fa-fw me-3"></i><span>    Usuarios</span></a>
                    <a asp-action="Iframe" asp-controller="Meteorology" class="list-group-item list-group-item-action py-2 ripple   etiquetas"><i style="color:dimgrey" class="bi bi-cloud-sun-fill fa-fw me-3"></i><span>    Meteorología</span></a>
                </div>
            </div>
        </nav>

    </header>
</body>

Nuvian_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}


<body class="imgLogin  ">


    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-white text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 ">

                            <div class="mb-md-5 mt-md-4 pb-5">

                                <div class="text-center"><img class="imgLogo " src="~/images/iconCIIADHEL2.png" /></div>

                                <div class="form-group">
                                    <label class="etiquetas" for="InputUsuario1">Usuario</label>
                                    <input type="text" pattern="[1-9]-?\d{4}-?\d{4}" maxlength="10" title="Formato: 1-2345-6789" class="form-control" required="" id="txtUsuario" onkeyup="validarDATA()" onkeypress="return (event.charCode >= 48 && event.charCode <= 57)">
                                    <h6 id="UserError" class="form-text text-muted"></h6>
                                </div>

                                <div class="form-group">
                                    <label class="etiquetas" for="InputPassword1">Contraseña</label>
                                    <input type="password" class="form-control" id="txtPassword" maxlength="25" onkeyup="validarDATA()" onkeypress="return (event.charCode >= 48 && event.charCode <= 57 || event.charCode >= 65 && event.charCode <= 90 || event.charCode >= 97 && event.charCode <= 122)" required>
                                    <h6 id="PasswordError" class="form-text text-muted"></h6>

                                </div>
                                <button type="submit" class="btn btn-primary btn-block btnIngresar" id="log">Ingresar</button>
                                <br />
                                <div class="form-group text-center">

                                    <a href="#" data-toggle="popover" title="Información" data-content="Comuníquese por correo electrónico a soportenuvian@rossmon.co.cr o bien comuníquese por vía telefónica con el administrador al +506 85903615">¿Olvidó su contraseña?</a>
                                    <br />
                                    <label id="errormsg" style="color:red;"></label>
                                </div>



                            </div>



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


</body>

@section Scripts{
    <script src="~/js/login.js"></script>



}

Nuvian_Web/Views/Meteorology/Iframe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<br />
<br />
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 text-center">  <p class="titulo ">METAR y TAF</p></div>
    <div class="col-sm-4"></div>
</div>
<div class="row">
    <div class="col">

    </div>
    <div class="col">
        <div class="form-group" id="gAeropuerto">
            <label class="etiquetas" for="lbAeropuerto">Aeropuerto</label>
            <select id="slAeropuerto" class="form-control js-example-basic-single  " onchange="CargarFrameParam()">
            </select>

        </div>
    </div>
    <div class="col">

    </div>
</div>





<div id="clima" class="row justify-content-center align-items-center">



</div>


@section Scripts{
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>


        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });
    </script>

    <script src="~/js/metar_taf.js"></script>



}

Nuvian_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nuvian_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="sweetalert2.min.js"></script>
    @*<link rel="stylesheet" href="sweetalert2.min.css">*@

    @RenderSection("Styles", required: false)
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3" style="background-color: #449FC7;">
            <div class="container">
                <a class="navbar-brand text-white" style="font-size:30px;" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/iconCIIADHEL2.png" height="50" alt="logo">NUVIAN</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <i style="color:white">Developed by IT Rossmon </i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.6/dist/sweetalert2.all.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Nuvian_Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nuvian_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<script src="sweetalert2.min.js"></script>*@
    @*<link rel="stylesheet" href="sweetalert2.min.css">*@

</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <i style="color:white">Developed by IT Rossmon </i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.6/dist/sweetalert2.all.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Nuvian_Web/Views/User/BasePage.cshtml
@{ ViewData["Title"] = "View";
                Layout = "~/Views/Shared/_Layout.cshtml"; }
@section Styles{
}
<partial name="NuevoUsuario" />
<hr />
<br />
<br />
<partial name="ListUsers" />
@section Scripts{
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#Users_table').DataTable();
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });
    </script>
    <script src="~/js/formulario.js"></script>
}

Nuvian_Web/Views/User/ListUsers.cshtml
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 text-center">  <p class="titulo ">Lista de usuarios</p></div>
    <div class="col-sm-4"></div>
</div>

<table id="Users_table" class="table table-striped">
    <thead style="background-color: #449FC7;">
        <tr class="titulo2">
            <th>ID</th>
            <th>Cédula</th>
            <th>Nombre</th>
            <th>Primer Apellido</th>
            <th>Segundo Apellido</th>
            <th>Aeropuerto</th>
            <th>Correo</th>
            <th>Fecha ingreso</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

Nuvian_Web/Views/User/NuevoUsuario.cshtml
@section Styles{

}

<br />
<br />
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4 text-center">  <p class="titulo ">Registro Usuarios</p></div>
    <div class="col-sm-4"></div>
</div>
<br />
<br />
<div class="formulario " id="formulario">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <input type="hidden" class="form-control" id="txtId_usr" name="txtId_usr">
            <div class="form-group" id="gIdentificacion">
                <label class="etiquetas" for="lbIdentificacion">Identificación</label>
                <input type="text" class="form-control" id="txtIdentificacion" name="txtIdentificacion">
                <p class="mensaje_error">El usuario debe contener solo números, máximo 10 dígitos</p>
            </div>

        </div>
        <div class="col">
            <div class="form-group" id="gPassword">
                <label class="etiquetas" for="lbPassword">Contraseña</label>
                <input type="password" class="form-control" id="txtPassword" name="txtPassword">
                <p class="mensaje_error">La contraseña debe contener solo caracteres alfanumericos, máximo 25 dígitos</p>
            </div>
        </div>
        <div class="col"></div>
    </div>




    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="form-group" id="gNombre">
                <label class="etiquetas" for="lbNombre">Nombre</label>
                <input type="text" class="form-control" id="txtNombre" name="txtNombre" maxlength="25">
                <p class="mensaje_error">El nombre debe contener solo letras, máximo 25 dígitos</p>
            </div>

        </div>
        <div class="col">
            <div class="form-group" id="gApellido1">
                <label class="etiquetas" for="lbApellido1">Primer Apellido</label>
                <input type="text" class="form-control" id="txtApellido1" name="txtApellido1" maxlength="25">
                <p class="mensaje_error">El primer apellido debe contener solo letras, máximo 25 dígitos</p>
            </div>
        </div>
        <div class="col"></div>
    </div>

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="form-group" id="gApellido2">
                <label class="etiquetas" for="lbApellido2">Segundo Apellido</label>
                <input type="text" class="form-control" id="txtApellido2" name="txtApellido2" maxlength="25">
                <p class="mensaje_error">El segundo apellido debe contener solo letras, máximo 25 dígitos</p>
            </div>

        </div>
        <div class="col">
            <div class="form-group" id="gCorreo">
                <label class="etiquetas" for="lbCorreo">Correo Electrónico</label>
                <input type="email" class="form-control" id="txtCorreo" name="txtCorreo" placeholder="example@gmail.com">
                <p class="mensaje_error">El correo debe tener como máximo 25 dígitos</p>
            </div>
        </div>
        <div class="col"></div>
    </div>

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="form-group" id="gTelefono">
                <label class="etiquetas" for="lbTelefono">Teléfono</label>
                <input type="text" class="form-control" id="txtTelefono" name="txtTelefono" placeholder="8888-8888">
                <p class="mensaje_error">El telefono debe contener solo números, máximo 10 dígitos</p>
            </div>
        </div>
        <div class="col">
            <div class="form-group" id="gFecha">
                <label class="etiquetas" for="lbFecha_nacimiento">Fecha Nacimiento</label>
                <input type="date" class="form-control" id="txtFecha_nacimiento" name="txtFecha_nacimiento">
                <p class="mensaje_error">La fecha de nacimiento es requerida</p>
            </div>

        </div>
        <div class="col"></div>
    </div>



    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="form-group" id="gAeropuerto">

                <label class="etiquetas" for="lbAeropuerto">Aeropuerto</label>
                <select id="slAeropuerto" class="form-control js-example-basic-single  " onchange="validarAeropuerto()">

               
                </select>
                <p class="mensaje_error">El aeropuerto es requerido</p>
            </div>

        </div>
        <div class="col">

        </div>
        <div class="col"></div>
    </div>


    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="form-group">
                <button id="btnGuardar" type="submit" class="btn btn-success btn-block" disabled="disabled">Guardar</button>
            </div>

        </div>
        <div class="col">
            <div class="form-group">
                <button type="button" class="btn btn-danger btn-block" id="btnCancelar">Cancelar</button>
            </div>
        </div>
        <div class="col"></div>
    </div>

</div>

@*<div class="col">
        <div class="form-group">
            <button id="btnEliminar" type="button" class="btn btn-danger btn-block">Eliminar</button>
        </div>
    </div>*@

@section Scripts{




}